package common.controllers.enums;
/**
 * enum class that present all the operation that the OBL do
 */
public enum OperationType {
Login,
SearchBook,
SearchSubscriber,
GetSubscriberDetails,
EditDetailsBySubscriber,
EditDetailsByLibrarian,
AddNewSubscriberByLibrarian,
SearchBookOnManageStock,
AddNewBook,
GetCopiesOfSelectedBook,
AddNewCopy,
DeleteCopy, 
UpdateBookDetails,
OrderBook,
BorrowBookByLibrarian, 
ReturnBookByLibrarian, 
Logout, 
ShowMyBorrowedBooks,
LossReporting,
DownloadTableOfContent, 
ShowBookPhoto,
GetStatstic, 
AddHistoryRecord, 
AutomaticBorrowExtenation,
GetActiviySnapshotByDate,
GetAllLatesReturnBySingleBookCatId,
GetLastActiviySnapshotRecord,
GetActiviySnapshotsByPeriod,
ShowBookPhotoOnSearchBookDetails, 
GetInboxMsg, makeAsRead, 
ExtensionBookByLibrarian, 
LockReaderCard, 
ChangeToActiveReaderCard,
GetBookStatstic,
}
